services:
  - type: web
    name: cardify-backend
    env: node
    plan: free
    rootDir: ./backend
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://cardif-y.vercel.app
      - key: CORS_ORIGINS
        value: https://cardif-y.vercel.app,https://www.cardif-y.vercel.app
      - key: SERVER_URL
        value: https://cardify-backend.onrender.com
      - key: MONGO_URI
        value: mongodb+srv://cardifyuser:bg1skvf3eZmQdLNh@cluster.mongodb.net/cardify
